name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
      - uses: actions/checkout@v2
        
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: saddambilalov
          password: ${{ secrets.SECRET_KEY }}
          repository: saddambilalov/apache-ranger
          tags: $(date +%s)
          tag_with_sha: true
          path: rokku-dev-apache-ranger
