name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: saddambilalov
          password: ${{ secrets.SECRET_KEY }}
          repository: saddambilalov/apache-ranger
          tag_with_ref: true
          path: rokku-dev-apache-ranger
