name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - run: |
          VERSION=$(date +%s)
          docker login -u saddambilalov -p ${{ secrets.SECRET_KEY }}
          docker build . --file ./rokku-dev-apache-ranger/Dockerfile --tag saddambilalov/apache-ranger:${VERSION}
          docker push saddambilalov/apache-ranger:${VERSION}
